import React from 'react';
import { createRoot } from 'react-dom/client';
import PortalShell from '@/components/portal/PortalShell';
import { PortalPageHeader,PortalEmpty } from '@/components/portal/PortalPage';
import { usePathname } from './navigation';
import type { PortalMember } from '@/lib/portal/auth';
import '@/app/globals.css';
import '@/app/workspace.css';
import '@/app/portal-design.css';
const member={fullName:'Örnek Mühendis',email:'fixture@example.test',role:'admin',teams:['CORE Systems']} as unknown as PortalMember;
function Registry(){return <><PortalPageHeader code="TEST" title="Proje çalışma alanları" lead="Takımın üzerinde çalıştığı projeler, sorumlular ve güncel durum." action={<button className="portalPrimaryButton">Proje oluştur</button>}/><div className="portalRegistryToolbar"><form onSubmit={e=>e.preventDefault()}><label className="grow"><span>Ara</span><input placeholder="Proje adı veya takım"/></label><label><span>Durum</span><select><option>Tüm durumlar</option></select></label><button>Filtrele</button></form><div className="portalRegistrySummary"><b>3</b><small>proje</small></div></div><div className="portalDataTableShell"><table className="portalDataTable"><thead><tr><th>Proje</th><th>Takım</th><th>Durum</th><th>Sorumlu</th><th>İşlemler</th></tr></thead><tbody>{['Otonom test platformu','Sensör doğrulama sistemi','Uzun proje adı ile taşma ve okunabilirlik kontrolü'].map((name,i)=><tr key={name}><td className="primaryCell"><div><b>{name}</b><small>Mühendislik prototipi · Revizyon {i+1}</small></div></td><td>CORE Systems</td><td><span className="portalStatusText active">Devam ediyor</span></td><td>Örnek Mühendis</td><td className="rowActions"><button>İncele</button><button>Düzenle</button></td></tr>)}</tbody></table></div><details className="portalToolSurface" style={{marginTop:24}}><summary>Proje bilgilerini düzenle</summary><form className="portalFormGrid" style={{padding:20}}><label><span>Proje adı</span><input defaultValue="Sensör doğrulama"/></label><label><span>Takım</span><select><option>CORE Systems</option></select></label><label className="portalFormWide"><span>Açıklama</span><textarea rows={4}/></label><button className="portalPrimaryButton" type="button">Kaydet</button></form></details></>}
function Dashboard(){return <><header className="portalDashboardHeader"><div><span>CORE / TODAY</span><h1>Merhaba, Mühendis.</h1><p>Bugünün işlerini ve dikkat isteyen konuları tek bakışta gör.</p></div></header><section className="portalDashboardMetricStrip">{['Açık görev','Bildirim','Toplantı','Düşük stok'].map((s,i)=><a key={s}><span>{s}</span><b>{[12,3,2,0][i]}</b><small>Güncel durum</small></a>)}</section><section className="portalDashboardGrid"><article className="portalDashboardPane"><header><b>Bana atanan işler</b><a>Görevler →</a></header><div className="portalCompactList">{['Sensör testini tamamla','Tasarım incelemesini paylaş'].map(s=><div key={s}><span className="portalPriority high">Yüksek</span><div><b>{s}</b><small>CORE Systems</small></div><em>Devam ediyor</em></div>)}</div></article><article className="portalDashboardPane"><header><b>Toplantılar ve takvim</b></header><PortalEmpty title="Bugün toplantın yok" text="Planladığın toplantılar burada listelenir."/></article></section></>}
function Mail(){return <div className="mailAppShell"><header className="mailAppTopbar"><div className="mailAppSectionTitle"><b>İç yazışma</b></div><input className="mailAppSearch" placeholder="Yazışmalarda ara"/><button className="portalPrimaryButton">Yeni yazışma</button></header><div className="mailAppBody"><aside className="mailAppRail"><a>Gelen kutusu</a><a>Gönderilenler</a></aside><section className="mailListPane"><div className="portalEmpty"><h3>Tasarım incelemesi</h3><p>Test planının son sürümü hazır.</p></div></section><section className="mailReaderPane"><div className="mailReaderEmpty"><h2>Bir yazışma seç</h2><p>İçeriği burada okuyabilirsin.</p></div></section></div></div>}
function App(){const route=usePathname();return <PortalShell member={member} canControl>{route==='/portal'?<Dashboard/>:route.startsWith('/portal/mail')?<Mail/>:<Registry/>}</PortalShell>}
createRoot(document.getElementById('root')!).render(<App/>);
