import React from 'react';
import ResizableWorkspace from '@/components/portal/ResizableWorkspace';
import { createRoot } from 'react-dom/client';
import PortalShell from '@/components/portal/PortalShell';
import PortalHome from '@/components/portal/PortalHome';
import PortalMobileRuntime from '@/components/portal/PortalMobileRuntime';
import PortalNativeExperience from '@/components/portal/PortalNativeExperience';
import { PortalPageHeader,PortalEmpty } from '@/components/portal/PortalPage';
import { usePathname, useFixtureLocation } from './navigation';
import ChatPage from '@/app/portal/(member)/chat/page';
import MailPage from '@/app/portal/(member)/mail/page';
import SecurityPage from '@/app/portal/(member)/security/page';
import type { PortalMember } from '@/lib/portal/auth';
import '@/app/globals.css';
import '@/app/portal.css';
const member={fullName:'Örnek Mühendis',email:'fixture@example.test',role:'admin',teams:['CORE Systems']} as unknown as PortalMember;
function Registry(){return <><PortalPageHeader code="TEST" title="Proje çalışma alanları" lead="Takımın üzerinde çalıştığı projeler, sorumlular ve güncel durum." action={<button className="portalPrimaryButton">Proje oluştur</button>}/><div className="portalRegistryToolbar"><form onSubmit={e=>e.preventDefault()}><label className="grow"><span>Ara</span><input placeholder="Proje adı veya takım"/></label><label><span>Durum</span><select><option>Tüm durumlar</option></select></label><button>Filtrele</button></form><div className="portalRegistrySummary"><b>3</b><small>proje</small></div></div><div className="portalDataTableShell"><table className="portalDataTable"><thead><tr><th>Proje</th><th>Takım</th><th>Durum</th><th>Sorumlu</th><th>İşlemler</th></tr></thead><tbody>{['Otonom test platformu','Sensör doğrulama sistemi','Uzun proje adı ile taşma ve okunabilirlik kontrolü'].map((name,i)=><tr key={name}><td className="primaryCell"><div><b>{name}</b><small>Mühendislik prototipi · Revizyon {i+1}</small></div></td><td>CORE Systems</td><td><span className="portalStatusText active">Devam ediyor</span></td><td>Örnek Mühendis</td><td className="rowActions"><button>İncele</button><button>Düzenle</button></td></tr>)}</tbody></table></div><details className="portalToolSurface" style={{marginTop:24}}><summary>Proje bilgilerini düzenle</summary><form className="portalFormGrid" style={{padding:20}}><label><span>Proje adı</span><input defaultValue="Sensör doğrulama"/></label><label><span>Takım</span><select><option>CORE Systems</option></select></label><label className="portalFormWide"><span>Açıklama</span><textarea rows={4}/></label><button className="portalPrimaryButton" type="button">Kaydet</button></form></details></>}
const empty=new URLSearchParams(location.search).has('empty');
function Dashboard(){return <PortalHome data={{name:'Tunahan',stats:[{label:'Açık görev',value:12,detail:'İş kuyruğunda',href:'/portal/tasks'},{label:'Bildirim',value:3,detail:'Okunmamış',href:'/portal/notifications'},{label:'Toplantı',value:2,detail:'Planlanan / canlı',href:'/portal/meetings'},{label:'Düşük stok',value:0,detail:'Kontrol bekliyor',href:'/portal/inventory'}],tasks:empty?[]:[{id:'1',title:'Sensör doğrulama testini tamamla',meta:'CORE Systems · Devam ediyor',href:'/portal/tasks/1',badge:'Yüksek',tone:'warning'},{id:'2',title:'Uzun görev başlığı: otonom platform için revizyon ve tasarım incelemesi',meta:'CORE Marine · İncelemede',href:'/portal/tasks/2',badge:'Normal'}],agenda:empty?[]:[{id:'3',title:'Haftalık tasarım incelemesi',meta:'30 Eyl 14:30 · CORE Embedded',href:'/portal/meetings/3'}],notifications:[],stock:[],activity:empty?[]:[{id:'4',title:'Tasarım dosyası güncellendi',meta:'Örnek Mühendis · 30 Eyl 11:45'}],vehicles:1,openPolls:2,pendingBudget:0}}/>}
function ServerPage(){const url=useFixtureLocation();const [content,setContent]=React.useState<React.ReactNode>(null);React.useEffect(()=>{let active=true;const searchParams=Promise.resolve(Object.fromEntries(new URLSearchParams(location.search)));const render=url.startsWith('/portal/chat')?ChatPage({searchParams}):url.startsWith('/portal/security')?SecurityPage():MailPage({searchParams});void render.then(result=>{if(active)setContent(result);});return()=>{active=false;};},[url]);return <>{content}</>;}
function Workbench(){return <ResizableWorkspace storageKey="fixture-panels" label="Mühendislik panelleri"><ResizableWorkspace mode="surface" storageKey="fixture-canvas" label="Çizim alanı"><div style={{height:'100%',background:'var(--core-surface-subtle)',padding:24}}>CAD / PCB önizleme alanı<textarea aria-label="Çalışma notu" placeholder="Boyut değiştirirken bu not korunur"/></div></ResizableWorkspace><aside className="portalPanel"><h2>Dosya bilgileri</h2><p>Revizyon ve inceleme notları</p></aside></ResizableWorkspace>}
const mobileConfig={appScheme:'ytucore',androidPackage:'test.core',iosBundleId:'test.core',appStoreUrl:'',playStoreUrl:'',appVersion:'test',handoffEnabled:true,baseUrl:location.origin};
function App(){const route=usePathname();return <><PortalShell member={member} canControl>{['/portal/mechanical','/portal/electronics','/portal/code-lab','/portal/repositories'].includes(route)?<Workbench/>:route==='/portal'?<Dashboard/>:['/portal/mail','/portal/chat','/portal/security'].some(path=>route.startsWith(path))?<ServerPage/>:<Registry/>}</PortalShell><PortalMobileRuntime config={mobileConfig}/><PortalNativeExperience memberName="Örnek Mühendis" memberRole="Yönetici" portalRole="admin" canControl memberInitials="ÖM" counts={{tasks:12,notifications:3,mail:2,chat:1}}/></>}
createRoot(document.getElementById('root')!).render(<App/>);
